kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install depends
    image: node:18
    commands:
      - npm install

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  # Other branches
  - name: test
    image: node:18
    commands:
      - npm run lint

volumes:
  - name: cache
    host:
      path: /tmp/imageify
