version: "3.4"

services:
  imageify:
    image: imageify
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./.storage:/.storage

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: imageify
      MONGO_INITDB_ROOT_PASSWORD: reallysecuremongopassword
    volumes:
      - ./mongodb:/data
