version: "3.4"

services:
  imageify:
    image: imageify
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 7769:3000
    user: root
    volumes:
      - ./.storage:/app/.storage

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: imageify
      MONGO_INITDB_ROOT_PASSWORD: reallysecuremongopassword
    ports:
      - 27017:27017
    user: root
    volumes:
      - ./mongodb:/data/db
